In [38]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import ast

In [40]:
df_train = pd.read_csv('../Dataset/concat_data_train.csv', sep=';')
# df_train["Photo"] = df_train["Photo"].apply(lambda x: np.array(ast.literal_eval(x)))
# print(type(df_train.iloc[0]["Photo"]))
print(df_train.iloc[0]["Photo"])
# df_train.head()

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [28]:
plt.matshow(df_train.iloc[0]["Photo"])

ValueError: not enough values to unpack (expected 2, got 0)

In [3]:
df_test = pd.read_csv('../Dataset/concat_data_test.csv')
df_test.head()

Photo;Label;Separation
0  [[0. 0. 0. ... 0. 0. 0.]\n [0. 0. 0. ... 0. 0....
1  [[0. 0. 0. ... 0. 0. 0.]\n [0. 0. 0. ... 0. 0....
2  [[0. 0. 0. ... 0. 0. 0.]\n [0. 0. 0. ... 0. 0....
3  [[0. 0. 0. ... 0. 0. 0.]\n [0. 0. 0. ... 0. 0....
4  [[0. 0. 0. ... 0. 0. 0.]\n [0. 0. 0. ... 0. 0....

In [5]:
df_validation = pd.read_csv('../Dataset/concat_data_validation.csv')
df_validation .head()

Empty DataFrame
Columns: [Photo;Label;Separation]
Index: []

In [37]:
truc = np.array([[3, 4, 5], [2, 3, 4]])
truc

array([[3, 4, 5],
       [2, 3, 4]])