In [8]:
import pandas as pd
import numpy as np
import ast

In [9]:
truc = np.array([[1, 3, 4], [3, 5, 56]])
truc

array([[ 1,  3,  4],
       [ 3,  5, 56]])

In [10]:
bidule = np.array2string(truc, separator=', ')
bidule = bidule.replace('\n', '')
bidule

'[[ 1,  3,  4], [ 3,  5, 56]]'

In [11]:
machin = np.array(ast.literal_eval(bidule))
machin

array([[ 1,  3,  4],
       [ 3,  5, 56]])

In [13]:
import numpy as np

# Création d'un tableau numpy
array = np.array([0.0, 0.1234567, 0.456, 0.131123], dtype=float)

# Ajuster le format d'impression avec des options personnalisées
np.set_printoptions() #formatter={'float': '{:0.8f}'.format})

# Convertir en chaîne
array_as_string = np.array2string(array, separator=", ")

print(array_as_string)

[0.  , 0.12, 0.46, 0.13]


In [19]:
import numpy as np

# Exemple de tableaux
array1 = np.array([1, 2, 3])
array2 = np.array([[4, 5, 6], [7, 8, 9]])

array1 = np.append(array1, 4)

# Sauvegarder plusieurs tableaux dans un fichier .npz
np.savez("arrays.npz", tableau1=array1, tableau2=array2)

# Charger les tableaux depuis le fichier .npz
data = np.load("arrays.npz")

print("type de data :", type(data))  # <class 'numpy.lib.npyio.NpzFile'>
print("Nom des tableaux :", data.files)  # ['tableau1', 'tableau2']*
print("tableau 1 :", data["tableau1"])  # [1 2 3]
print("tableau 2 :", data["tableau2"])  # [[4 5 6] [7 8 9]]

type de data : <class 'numpy.lib.npyio.NpzFile'>
Nom des tableaux : ['tableau1', 'tableau2']
tableau 1 : [1 2 3 4]
tableau 2 : [[4 5 6]
 [7 8 9]]


In [18]:
import sys

data = np.load("https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz")

# Inspecter les clés du fichier
print(data.files)

print(sys.getsizeof(data))

OSError: [Errno 22] Invalid argument: 'https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz'

In [22]:
print("../Dataset")
print("   /dataset")
print("      /test")
print("        /M")

../Dataset
   /dataset
      /test
        /M
