In [4]:
import pandas as pd
import numpy as np
import ast
import numpy as np
from pymongo import MongoClient

In [9]:
truc = np.array([[1, 3, 4], [3, 5, 56]])
truc

array([[ 1,  3,  4],
       [ 3,  5, 56]])

In [10]:
bidule = np.array2string(truc, separator=', ')
bidule = bidule.replace('\n', '')
bidule

'[[ 1,  3,  4], [ 3,  5, 56]]'

In [11]:
machin = np.array(ast.literal_eval(bidule))
machin

array([[ 1,  3,  4],
       [ 3,  5, 56]])

In [13]:
import numpy as np

# Création d'un tableau numpy
array = np.array([0.0, 0.1234567, 0.456, 0.131123], dtype=float)

# Ajuster le format d'impression avec des options personnalisées
np.set_printoptions() #formatter={'float': '{:0.8f}'.format})

# Convertir en chaîne
array_as_string = np.array2string(array, separator=", ")

print(array_as_string)

[0.  , 0.12, 0.46, 0.13]


In [19]:
import numpy as np

# Exemple de tableaux
array1 = np.array([1, 2, 3])
array2 = np.array([[4, 5, 6], [7, 8, 9]])

array1 = np.append(array1, 4)

# Sauvegarder plusieurs tableaux dans un fichier .npz
np.savez("arrays.npz", tableau1=array1, tableau2=array2)

# Charger les tableaux depuis le fichier .npz
data = np.load("arrays.npz")

print("type de data :", type(data))  # <class 'numpy.lib.npyio.NpzFile'>
print("Nom des tableaux :", data.files)  # ['tableau1', 'tableau2']*
print("tableau 1 :", data["tableau1"])  # [1 2 3]
print("tableau 2 :", data["tableau2"])  # [[4 5 6] [7 8 9]]

type de data : <class 'numpy.lib.npyio.NpzFile'>
Nom des tableaux : ['tableau1', 'tableau2']
tableau 1 : [1 2 3 4]
tableau 2 : [[4 5 6]
 [7 8 9]]


In [18]:
import sys

data = np.load("https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz")

# Inspecter les clés du fichier
print(data.files)

print(sys.getsizeof(data))

OSError: [Errno 22] Invalid argument: 'https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz'

In [22]:
print("../Dataset")
print("   /dataset")
print("      /test")
print("        /M")

../Dataset
   /dataset
      /test
        /M


In [5]:
from PIL import Image

# Ouvrir une image
image = Image.open("../Dataset/dataset/test/A/000000.png")

# Effectuer une rotation (exemple : 45 degrés)
image_rotated = image.rotate(270, expand=True)

# Afficher l'image après rotation
image_rotated.show()

# Sauvegarder l'image après rotation
image_rotated.save("./img/A_rotated.png")

In [3]:
# Connexion à MongoDB
client = MongoClient("mongodb://localhost:27017/Scibio")  # Remplacez par l'URL de votre serveur MongoDB
db = client["Scribio"]  # Nom de la base de données
collection = db["Test"]  # Nom de la collection

In [7]:
# Créer un tableau NumPy
tableau_numpy = np.array([[1, 2, 3], [4, 5, 6]])

# Convertir le tableau NumPy en une liste
tableau_liste = tableau_numpy.tolist()

# Insérer le tableau dans MongoDB
document = {"nom_tableau": "mon_tableau", "donnees": tableau_liste}
resultat = collection.insert_one(document)

# Afficher l'ID du document inséré
print("Document inséré avec l'ID :", resultat.inserted_id)


Document inséré avec l'ID : 677fdada94491e5e74338b8f


In [4]:
# Récupérer le document depuis MongoDB
document_recupere = collection.find({"nom_tableau": "mon_tableau"})
df = pd.DataFrame(list(document_recupere))
print(type(df.iloc[0]["donnees"]))
df



<class 'list'>


_id  nom_tableau                 donnees
0  677fd90b94491e5e74338b8c  mon_tableau  [[1, 2, 3], [4, 5, 6]]
1  677fdad894491e5e74338b8d  mon_tableau  [[1, 2, 3], [4, 5, 6]]
2  677fdad994491e5e74338b8e  mon_tableau  [[1, 2, 3], [4, 5, 6]]
3  677fdada94491e5e74338b8f  mon_tableau  [[1, 2, 3], [4, 5, 6]]

In [3]:
from tqdm import tqdm # progress bar
import time
# Parcours et transformation des photos avec barre de progression 
with tqdm(total=25, desc="Proccessing" , position=0, leave=True) as pbar:
    for i in range(50):
        time.sleep(1)
        pbar.update(1) # Mettre à jour la barre de progression

Proccessing: 50it [00:50,  1.00s/it]                        


In [5]:
img = Image.open("../Dataset/dataset/test/A/000000.png") # 300 x 300
nouvelle_taille = (50, 50) # 2500
img_redimensionnee = img.resize(nouvelle_taille) # Redimensionner l'image
nb_image = img_redimensionnee.convert('L') # Convertion en noir et blanc

NameError: name 'Image' is not defined